version: "3"
services:

  database_microservices:
    image: 'mysql:8'
    environment:
      - 'MYSQL_DATABASE=db_microServico'
      - 'MYSQL_PASSWORD=a22kju99z'
      - 'MYSQL_ROOT_PASSWORD=a22kju99z'
      - 'MYSQL_USER=mhqa_quinteiro'
    ports:
      - 3306:3306
    volumes:
      - /app/database/db_microServico

  ms_delivery:
    build: /Backend/Delivery
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database_microservices:3306/db_microServico
      - SPRING_DATASOURCE_USERNAME=mhqa_quinteiro
      - SPRING_DATASOURCE_PASSWORD=a22kju99z
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - spring.datasource.driver-class-name=com.mysql.jdbc.Driver
      - spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - database_microservices
    restart: on-failure
  
  ms_produtos:
    build: /Backend/Produtos
    ports:
      - 8082:8082
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database_microservices:3306/db_microServico
      - SPRING_DATASOURCE_USERNAME=mhqa_quinteiro
      - SPRING_DATASOURCE_PASSWORD=a22kju99z
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - spring.datasource.driver-class-name=com.mysql.jdbc.Driver
      - spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - database_microservices
    restart: on-failure
   

  ms_logistica:
    build: /Backend/Logistica
    ports:
      - 8083:8083
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database_microservices:3306/db_microServico
      - SPRING_DATASOURCE_USERNAME=mhqa_quinteiro
      - SPRING_DATASOURCE_PASSWORD=a22kju99z
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - spring.datasource.driver-class-name=com.mysql.jdbc.Driver
      - spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - database_microservices
    restart: on-failure
   

  ms_cliente:
    build: /Backend/Cliente
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database_microservices:3306/db_microServico
      - SPRING_DATASOURCE_USERNAME=mhqa_quinteiro
      - SPRING_DATASOURCE_PASSWORD=a22kju99z
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - spring.datasource.driver-class-name=com.mysql.jdbc.Driver
      - spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - database_microservices
    restart: on-failure

  database_financeiro:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=db_financeiro'
      - 'POSTGRES_PASSWORD=mh8q23pr99'
      - 'POSTGRES_USER=mhqa'
    ports:
      - 5432:5432
    volumes:
      - /app/database/postgre
    restart: on-failure

  ms_financeiro:
    build: /Backend/database_financeiro
    ports:
      - 8085:8085
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database_financeiro:5432/db_financeiro
      - SPRING_DATASOURCE_USERNAME=mhqa
      - SPRING_DATASOURCE_PASSWORD=mh8q23pr99
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - database_financeiro
    restart: on-failure   
    
  ms_pagamento:
    build: /Backend/Financeiro
    ports:
      - 8084:8084
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database_financeiro:5432/db_financeiro
      - SPRING_DATASOURCE_USERNAME=mhqa
      - SPRING_DATASOURCE_PASSWORD=mh8q23pr99
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - database_financeiro
    restart: on-failure


